"""add trip status and reject_reason

Revision ID: 7856932b318f
Revises: 20260302_0006
Create Date: 2026-03-02 04:23:23.735495
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '7856932b318f'
down_revision = '20260302_0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('status', sa.String(), nullable=False, server_default='pending_review'))
    op.add_column('trip', sa.Column('reject_reason', sa.String(), nullable=True))
    op.create_index(op.f('ix_trip_status'), 'trip', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_status'), table_name='trip')
    op.drop_column('trip', 'reject_reason')
    op.drop_column('trip', 'status')
    # ### end Alembic commands ###
